FROM signoz/signoz-otel-collector:v0.144.2

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
COPY signoz/otel-collector-opamp-config.yaml /etc/manager-config.yaml

CMD ["--config=/etc/otel-collector-config.yaml", "--manager-config=/etc/manager-config.yaml", "--copy-path=/var/tmp/collector-config.yaml"]
